apiVersion: v1
kind: Service
metadata:
    name: "fitcluster"
    labels:
        app: "fitcluster"
spec:
    type: LoadBalancer
    ports:
    - port: 4641
      targetPort: 4641
      protocol: TCP
      name: http
    selector:
        app: "fitcluster"